version: "3"
networks:
  ogani:
   driver: bridge
   ipam:
     config:
       - subnet: 172.18.0.0/24
         gateway: 172.18.0.1 

volumes:
  rabbit:
  mongodb:  
  oganiapi:
  mssql:
  elasticsearch:
  
services:
  mssql-ogani:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: mssql-ogani
   restart: always
   networks:
    ogani:
     ipv4_address: 172.18.0.2
   volumes:
    - mssql:/var/opt/mssql
   ports:
    - "1434:1433" 
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=!Dquery20@4
    - MSSQL_PID=Developer
    
  rabbitmq-ogani:
   image: rabbitmq:3-management
   container_name: rabbitmq-ogani
   restart: always
   networks:
     ogani:
      ipv4_address: 172.18.0.3
   volumes:
     - rabbit:/app/wwwroot
   ports:
     - "5672:5672" 
     - "15672:15672" 
   environment:
     - RABBITMQ_DEFAULT_USER=admin 
     - RABBITMQ_DEFAULT_PASS=password

  mongo-ogani:
   image: mongo:5.0.15-focal
   container_name: mongo-ogani
   restart: always
   networks:
    ogani:
     ipv4_address: 172.18.0.4
   volumes:
    - mongodb:/data/db
   ports:
    - "27017:27017"
   environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
  
  elasticsearch-ogani:
   container_name: elasticsearch-ogani
   image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
   ports:
    - 9200:9200
   volumes:
    - elasticsearch:/usr/share/elasticsearch/data
   environment:
    - cluster.name=elastic
    - ELASTIC_PASSWORD=elastic
    - xpack.license.self_generated.type=basic
    - node.name=es01
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms4g -Xmx4g
    - xpack.security.enrollment.enabled=true
   networks:
     ogani:
       ipv4_address: 172.18.0.5

  kibana-ogani:
    container_name: kibana-ogani
    image: docker.elastic.co/kibana/kibana:8.14.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-ogani
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
      ogani:
        ipv4_address: 172.18.0.6
    extra_hosts:
     - elastic.ogani.az:172.18.0.5

  ogani-api:
   image: ogani-api:v1
   build:
    context: .
    dockerfile: ./src/Presentation/WebApi/Dockerfile
   container_name: ogani-api
   restart: always
   networks:
    ogani:
     ipv4_address: 172.18.0.10
   volumes:
    - oganiapi:/app/wwwroot
   ports:
    - 5080:80
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - SUPERADMIN_USER=kamranAeff
    - SUPERADMIN_EMAIL=akamran@code.edu.az
    - SUPERADMIN_PASSWORD=!Dquery20@4
    - SOURCE_URL=http://localhost:5080
    - JWT__KEY=88b0ba2aaff3daa419917a9a1c85732570c4771b
    - JWT__ISSUER=api.ogani.az
    - JWT__AUDIENCE=api.ogani.az
    - JWT__EXPIRATIONDURATIONMINUTES=10
    - RABBIT_URL=amqp://admin:password@rabbit.ogani.az:5672
    - "ConnectionStrings__cString=Data Source=sql.ogani.az;Initial Catalog=OganiDb;User Id=sa;Password=!Dquery20@4;MultipleActiveResultSets=False;Encrypt=false;App=OganiWebApp"
    - "Serilog__WriteTo[1]__Args__databaseUrl=mongodb://admin:password@mongo.ogani.az/ogani?authSource=admin&authMechanism=SCRAM-SHA-1"
    - "ELASTIC_URL=https://elastic.ogani.az:9200"
    - "ELASTIC_USER=elastic"
    - "ELASTIC_PASSWORD=elastic"
   extra_hosts:
    - sql.ogani.az:172.18.0.2
    - rabbit.ogani.az:172.18.0.3
    - mongo.ogani.az:172.18.0.4
    - elastic.ogani.az:172.18.0.5

  ogani-ui:
   image: ogani-ui:v1
   build:
    context: .
    dockerfile: ./src/Presentation/WebUI/Dockerfile
   container_name: ogani-ui
   restart: always
   networks:
    ogani:
     ipv4_address: 172.18.0.11
   ports:
    - "5081:80"
   environment: 
    - ASPNETCORE_ENVIRONMENT=Production
    - API_URL=http://api.ogani.az
   extra_hosts:
    - api.ogani.az:172.18.0.10