//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Localization.CommonResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI.Localization.CommonResources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağazamız haqqında.
        /// </summary>
        public static string AboutOurShop {
            get {
                return ResourceManager.GetString("AboutOurShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haqqımızda.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paylaşımlar.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markalar.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampaniyalar.
        /// </summary>
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriyalar.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rənglər.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müraciət.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çatdırılma məlumatı.
        /// </summary>
        public static string DeliveryInfomation {
            get {
                return ResourceManager.GetString("DeliveryInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ən son mağazamız və xüsusi təkliflər haqqında e-poçt yeniləmələri alın.
        /// </summary>
        public static string GetMailUpdatesAboutOurLatestShopAndSpecialOffers {
            get {
                return ResourceManager.GetString("GetMailUpdatesAboutOurLatestShopAndSpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana səhifə.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenilik.
        /// </summary>
        public static string Innovation {
            get {
                return ResourceManager.GetString("Innovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bülletenimizə indi qoşulun.
        /// </summary>
        public static string JoinOurNewsletterNow {
            get {
                return ResourceManager.GetString("JoinOurNewsletterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil ol.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tükənmək üzrə olan məhsullar.
        /// </summary>
        public static string LowStockItems {
            get {
                return ResourceManager.GetString("LowStockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əməliyyat.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xidmətlərimiz.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayt xəritəmiz.
        /// </summary>
        public static string OurSitemap {
            get {
                return ResourceManager.GetString("OurSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gözləmədə.
        /// </summary>
        public static string PendingPosts {
            get {
                return ResourceManager.GetString("PendingPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məxfilik siyasəti.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsullar.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layihələr.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dərc edilmişlər.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İmtina edilib.
        /// </summary>
        public static string RejectedPosts {
            get {
                return ResourceManager.GetString("RejectedPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təhlükəsiz alış-veriş.
        /// </summary>
        public static string SecureShopping {
            get {
                return ResourceManager.GetString("SecureShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tənzimləmələr.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mağaza.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçülər.
        /// </summary>
        public static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abunə ol.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/24 dəstək.
        /// </summary>
        public static string Support_24_7 {
            get {
                return ResourceManager.GetString("Support_24_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təqlər.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəylər.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faydalı Linklər.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz kimik.
        /// </summary>
        public static string WhoWeAre {
            get {
                return ResourceManager.GetString("WhoWeAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt adresiniz.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
    }
}
